language: python
python:
    - "2.7"

before_install:
  - wget https://chromedriver.googlecode.com/files/chromedriver_linux32_20.0.1133.0.zip
  - unzip chromedriver_linux32_20.0.1133.0.zip

install: python -m pip install -r requirements.txt
env:
    - CONFIG_PATH=blog.config.TravisConfig
addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
before_script:
    - psql -c 'create database "blogful-test";' -U postgres
script:
    - PYTHONPATH=. python tests/test_filters.py
    - PYTHONPATH=. python tests/test__views_integration.py
    - PYTHONPATH=. python tests/test_views_acceptance.py